"""add document analysis

Revision ID: f4c1404021f8
Revises: a723e9d4b030
Create Date: 2026-08-21 18:11:03.871537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4c1404021f8'
down_revision = 'a723e9d4b030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_analyses')
    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('important_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_topics', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['document_id'])
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('key_topics')
        batch_op.drop_column('important_points')
        batch_op.drop_column('summary')

    op.create_table('document_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('important_points', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_concepts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('important_clauses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_analyses_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_analyses_pkey')),
    sa.UniqueConstraint('document_id', name=op.f('document_analyses_document_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
